resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: myGithub
      path: jfrog/jfrog-pipelines-simple-example     # replace jfrog with your username or org name
      branches:
        include: master
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: myArt
      buildName: SampleApp
      buildNumber: 1          
pipelines:  
  - name: basic_pipeline_xray
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello"  
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepo
          outputResources:
            - name: myBuildInfo             
        execution:
          onExecute:
            - echo $my_env_var

      - name: xrayScanStep
        type: XrayScan
        configuration:
          inputResources:
            - name: myBuildInfo 
