resources:
  - name: script_gh
    type: GitRepo
    configuration:
      path: RjSH1/sample-script
      gitProvider: myGithub
      #branches:
        #include: ^{{gitBranch}}$

pipelines:     
  - name: simple_jenkins_demo
    steps:
      - name: jenkins
        type: Jenkins
        configuration:
          inputResources:
            - name: script_gh
          jenkinsJobName: testPipeline
          integrations:
            - name: myJenkins
      
      - name: step_A
        type: Bash
        configuration:
          inputSteps:
            - name: jenkins
        execution:
          onExecute:
            - echo "Executing step_A"
