template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  # Sample Go app in a GitRepo
  - name: go_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      branches:
        include: main
      gitProvider: {{ .Values.gitProvider }}

  # Build info for the published Go app
  - name: go_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}    

  - name: artifactory_go_module_example
    type: GitRepo
    configuration:
      path: RjSH1/artifactory-go-example
      #branches:
        #include: master
      gitProvider: {{ .Values.gitProvider }}

pipelines:
  - name: go_publish_binary_example
    steps:
      # Build the Go sample app from the GitRepo. Docs at https://www.jfrog.com/confluence/display/JFROG/GoBuild
      - name: build_go
        type: GoBuild
        configuration:
          sourceLocation: .
          resolverRepo: go-virtual
          noRegistry: true
          inputResources:
            - name: go_repo
          integrations:
            - name: {{ .Values.artifactory }}
             
      # Publish the Go sample app binary to Artifactory
      - name: cicd_go_publish_binary
        type: GoPublishBinary
        configuration:
          # affinityGroup: goGroup
          # forceXrayScan: true
          # failOnScan: false
          autoPublishBuildInfo: true
          inputSteps:
            - name: build_go
          targetRepository: go-local
          integrations:
            - name: {{ .Values.artifactory }}
          outputResources:
            - name: go_buildinfo

      - name: publish_go_moduletest
        type: GoPublishModule
        execution:
          onStart:
            - go version
        configuration:  
#           environmentVariables: # optional
#             JFROG_CLI_BUILD_NAME: "go_test"
#             JFROG_CLI_BUILD_NUMBER: 2387
          sourceLocation: .  # required
          version: v0.0.0           # required
          targetRepository: go-local
          autoPublishBuildInfo: false
          integrations:
            - name: {{ .Values.artifactory }}
#           runtime: 
#             type: image
#             image: 
#               auto:
#                 language: go
#                 versions:
#                   - "1.15.2-f2674"
          inputResources:
            - name: artifactory_go_module_example
          #outputResources:
            #- name: go_build_info_publish_moduletest
